version: '3.7'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3006:3006"  # Internal use only
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
    command: ["node", "app.js"]
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"  
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

