version: '3.7'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3006:3006"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=production
    volumes:
      - .:/app  # Enable live reload during development if needed
      - /app/node_modules  # Prevent overwriting node_modules
    command: ["node", "app.js"]
