name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up SSH for remote deployment
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 3: Pull latest code and build the Docker image, then deploy using Docker Compose
      - name: Build Docker Image and Deploy via Docker Compose
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          echo "Starting Deployment..."
          ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << 'EOF'
            set -e

            cd /home/ec2-user/sample-node-project

            sudo systemctl start docker
            sudo systemctl enable docker
            
            # Pull latest changes from the repository
            git pull origin main
            echo "Git pull completed!"

            # Stop, remove existing containers, and clean up unused Docker resources
            docker compose down
            docker system prune -af

            # Build the Docker image
            IMAGE_TAG=$(git rev-parse --short HEAD)
            docker build -t sample-node-project:$IMAGE_TAG .

            # Build and start containers using Docker Compose (uses the built image)
            docker compose up --build -d

            echo "Docker Compose Deployment completed successfully!"
          EOF

      # Step 4: Handle build and deployment failures
      - name: Notify on failure
        if: failure()
        run: |
          echo "Build or deployment failed. Check the logs on the server."
